### ISSUE TITLE
Bug 002: Error with Score to Level Select Screen

### ISSUE THREAD

**Issue by LuciferPatronGod** [MorganMcLaren/HeiBai_Game#3]
Score gained/stars collected variable will not communicate with the Level Screen; produces code error.

Version
HeiBai v0.0.6

To Reproduce
1. Attempted to code score communication with Level Screen
2. Code test run begins
3. Error "Assets\Heibei\Scripts\NextLevel.cs(20,9): error CS0103: The name 'stars' does not exist in the current context" Is shown.

Expected behavior
Level screen should show 1 of 4 variables; "No stars", "1 star", "2 stars" or "3 stars" on the level select screen

Desktop System (please complete the following information):
- OS: Windows10

Additional context
This error is seen in code and UI errors, not in direct play testing.

**Comment by MorganMcLaren** [comment]
This error has been corrected by changing from using GetComponent to using a static variable for the collected stars.
